using PickleballGenie.Models;

namespace PickleballGenie.Data;

/// <summary>
/// The single source of truth for the curated drill catalog, shared by the
/// Scraper (which dedupes against the database by Title) and DbSeeder (which
/// dedupes by Id). Ids are pinned to the a1000000-...-00NN sequence so DbSeeder
/// can insert only the missing rows on databases seeded before a drill existed.
/// When adding drills, extend the Guid sequence past the current maximum —
/// never renumber or reuse an Id, and keep Titles unique across the list.
/// Categories must be one of the nine strings used by the self-rating feedback
/// loop: Dinking, Drops, Volleys, Serving, Returns, Lobs, Resets, Attacking,
/// Movement, General.
/// </summary>
public static class CuratedDrills
{
    // Factory method rather than a cached list: callers attach these instances
    // to different DbContexts, so each caller needs fresh untracked objects.
    public static List<Drill> GetAll() => new()
    {
        // 2.0 — New to the game. Deliberately solo-friendly: players without
        // access to coaching usually don't have a drilling partner either.
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000017"), Title = "Serve 20 In a Row", Category = "Serving", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill — all you need is a bucket of balls. From behind the baseline, serve into the correct service box 20 times in a row, using either a traditional underhand serve or the easier drop serve. Any depth counts; you're building a repeatable motion. Miss? Restart the count and track your best streak week to week.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000018"), Title = "Wall Dink Touch", Category = "Dinking", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill — any solid wall works. Mark a line at net height (34 inches). Stand about 7 feet back and softly dink above the line, letting the ball bounce between hits. Goal: 25 controlled dinks in a row. Soft grip, paddle out front, and bend your knees — not your wrist.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000019"), Title = "Drop, Bounce, Hit", Category = "General", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill for brand-new players. Drop the ball, let it bounce, and hit an easy forehand groundstroke across the court; collect and repeat, then switch to backhand. 20 each side. You're learning the paddle face, the contact point, and how the ball comes off the court — the foundation for everything else.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000020"), Title = "Let It Bounce: Return Habits", Category = "Returns", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "With a partner feeding easy serves (or a ball rebounding off a wall), practice the two-bounce habit: let the serve bounce, return it, and call the bounce out loud. Ten returns from each side. This builds the rule into your reflexes before match play, where volleying the serve is the classic new-player fault.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000025"), Title = "Kitchen Line Self-Feed Dinks", Category = "Dinking", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Stand at the kitchen line with a bucket of balls. Drop a ball, let it bounce, and dink it over the net so it lands inside the opposite kitchen. 10 forehand, 10 backhand, counting how many land in. Watch the arc: the ball should peak on your side of the net and fall softly. Goal: 7 of 10 per side.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000026"), Title = "Toss and Drop Landing Zone", Category = "Drops", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill introducing the soft game. From mid-court, drop a ball, let it bounce, and hit a gentle, lifting shot that arcs over the net and lands in the kitchen. Don't worry about perfection — you're learning that soft can be a weapon. 20 attempts, count your makes, and try to beat your score next session.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000027"), Title = "Self-Toss Volley Basics", Category = "Volleys", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Stand a step behind the kitchen line, toss a ball gently in front of you at chest height, and volley it over the net before it bounces — a short punch, no backswing. Return to ready position (paddle up, centered) after every hit. 15 forehand volleys, 15 backhand. The habit you're building is paddle-up readiness, not power.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000028"), Title = "Serve to Both Boxes", Category = "Serving", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Alternate serving from the right and left side of the baseline into the diagonally opposite service box, just like a real game. 10 serves per side, then repeat. This cements which box the serve must land in and gets both starting positions feeling normal before match play. Count total makes out of 20.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000029"), Title = "Wall Return Rehearsal", Category = "Returns", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Throw or hit a ball firmly at a wall from about 15 feet, let the rebound bounce once, then hit a smooth, full return stroke aiming high over an imaginary net. The wall plays the server; you build the see-bounce-swing rhythm of the return. 15 forehands, 15 backhands. Depth beats power — finish your swing toward your target.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000030"), Title = "Side Shuffle Line Touches", Category = "Movement", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill, no ball needed. Start at the center of the kitchen line in ready position, paddle up. Side-shuffle to touch the left sideline, shuffle back through center to the right sideline, and repeat — never crossing your feet, staying low. 5 rounds of 30 seconds with rest between. Balanced lateral movement is what keeps beginners from lunging at the kitchen line.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000031"), Title = "Paddle Ball Control Basics", Category = "General", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill you can do anywhere. Bounce the ball upward off your paddle face: 25 in a row on the forehand face, 25 on the backhand face, then alternate faces every hit. Once that's easy, bounce it low (knee height) and then high (above your head) on command. This is raw paddle feel — the touch every other shot is built on.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000032"), Title = "Court Zones Drop-Hit Targets", Category = "General", TargetDUPRLevel = 2.0m, EstimatedDurationMinutes = 10,
            Description = "Solo drill that teaches the court's geography. Mentally divide the opposite court into three zones: kitchen, mid-court, and back third. Drop-hit 10 balls into each zone on purpose, calling the zone before you swing. Keeping score by zone shows you that placement — not power — is what the game rewards, and it builds the aim you'll need for every level above this one.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        // 2.5 — Advanced beginner
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000021"), Title = "Deep Serve Targets", Category = "Serving", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Place a towel or cones across the back third of the service box. Serve 10 balls at each box, counting how many land deep past your marker. Goal: 7 of 10. A deep serve keeps the returner pinned back and buys you time — the first serve upgrade that wins points at this level.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000022"), Title = "Wall Volley Control", Category = "Volleys", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Stand 7–8 feet from a wall, paddle up in ready position, and volley continuously without letting the ball bounce. Start forehand-only, then alternate forehand and backhand. Goal: 25 in a row under control. Keep a short, compact punch — no backswing.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000023"), Title = "Baseline to Kitchen Footwork", Category = "Movement", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Start at the baseline, shadow a return, then advance toward the kitchen line in controlled steps with a split-step each time an imaginary opponent would strike the ball. Touch the line, backpedal to mid-court, split-step, and come forward again. 10 trips. Court movement is a skill — practice it like one.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000024"), Title = "Cooperative Dink Rally to 20", Category = "Dinking", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Partner drill. Both players at the kitchen line, dinking cross-court cooperatively — the goal is keeping the rally alive, not winning it. Count out loud to 20, then switch to the other diagonal. If a ball pops up high, catch it and restart. Height discipline now becomes attack prevention later.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000033"), Title = "Mid-Court Drop Self-Feed", Category = "Drops", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. From the transition zone (mid-court), drop a ball, let it bounce, and hit a soft drop that lands in the kitchen. The swing is a gentle lift from the shoulder, finishing toward your target. 10 from the middle, 10 from each sideline. Goal: 6 of 10 landing in the kitchen. This is the third shot drop in embryo — grooved before anyone is pressuring you.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000034"), Title = "Forehand-Backhand Wall Volley Ladder", Category = "Volleys", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. From 7–8 feet off a wall, volley in a fixed pattern: two forehands, two backhands, repeating without a bounce. When you can do 20 in the pattern, tighten it to strict alternation — one forehand, one backhand. The switch between faces is where beginners get caught flat-footed; this ladder makes the grip and paddle transition automatic.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000035"), Title = "Serve Placement: Wide and T", Category = "Serving", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Place a cone in the wide corner and another at the T (center line) of each service box. Serve 5 balls at each target, alternating, for 20 total. Score a point when the ball lands within a paddle's length of the cone. Placement pulls the returner off balance before the rally even starts — the first tactical serve skill.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000036"), Title = "Deep Return off the Wall", Category = "Returns", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. Hit a firm ball into a wall from 15–20 feet so the rebound comes back like a serve, let it bounce, and return it high and deep toward a target zone marked in the back third of the court (or on the wall above net height). 20 reps, counting deep landings. A deep return keeps the serving team pinned back — the single biggest return upgrade at this level.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000037"), Title = "Lob Landing Zone Practice", Category = "Lobs", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill introducing the lob. From the kitchen line, drop-hit lobs that clear an imaginary reaching opponent (aim 12+ feet high) and land in the back third of the court. Mark the back third with cones or a towel. 20 attempts, counting makes. Too short gets smashed, too long is out — this drill builds the height-plus-depth window that makes a lob safe.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000038"), Title = "Wall Soft Hands Absorb", Category = "Resets", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill — the first reset. Hit a ball firmly into the wall from close range, then catch the fast rebound on your paddle with a loose grip and soft, giving hands so the ball pops up gently in front of you instead of rocketing off. Re-hit firm, absorb soft, repeat. 3 sets of 10. Loosening your grip under incoming pace is the foundation of every reset you'll ever hit.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000039"), Title = "Overhead Smash Introduction", Category = "Attacking", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill. From mid-court, toss a ball high above your head, turn sideways, point at the ball with your free hand, and hit a controlled overhead into the deep half of the opposite court. Control first, power later — a smash into the net wins nothing. 20 reps. Add a target zone once 15 of 20 are landing in.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000040"), Title = "Split-Step Rhythm Drill", Category = "Movement", TargetDUPRLevel = 2.5m, EstimatedDurationMinutes = 10,
            Description = "Solo drill, no ball needed. Shadow a rally: split-step (a small hop onto the balls of both feet) at the moment an imaginary opponent hits, then push off in one of four directions — left, right, forward, back — recover to center, and split-step again. 3 rounds of 45 seconds. The split-step is the single habit that separates players who arrive on time from players who lunge.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        // 3.0 — Beginner
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000001"), Title = "Cross-Court Dink Rally", Category = "Dinking", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Stand at the kitchen line and sustain a cross-court dinking rally with a partner. Focus on soft hands, a continental grip, and keeping the ball below net height. Rally for 50 consecutive dinks before moving to backhand side.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000002"), Title = "Serve and Stay In", Category = "Serving", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Practice a consistent, deep serve targeting the back third of the service box. Partner returns; server focuses on a controlled third shot. Repeat 20 times each side. Consistency over power.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000003"), Title = "Kitchen Line Volley Exchange", Category = "Volleys", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Both players at the kitchen line exchanging slow, controlled volleys. Goal is zero errors in 30 consecutive exchanges. Keep paddle up, ready position after every shot.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000004"), Title = "Return of Serve Deep Target", Category = "Returns", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Server feeds consistent serves. Returner practices driving deep returns to the server's backhand corner. Goal: 8 of 10 returns land in the back third. Advance to kitchen after return.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000041"), Title = "Third Shot Drop Introduction", Category = "Drops", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Partner feeds a deep return from the kitchen line; you hit a drop from mid-court that lands softly in the kitchen, then step in. Once 6 of 10 land, move back toward the baseline and repeat. Learning the drop from mid-court first shortens the distance and builds confidence before the full baseline version.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000042"), Title = "Volley Depth Control", Category = "Volleys", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Both players at the kitchen line. Partner feeds medium-pace volleys; you alternate on command between blocking the ball short (dropping it into the kitchen) and pushing it deep at their feet or past them. 3 sets of 20. Controlling where a volley goes — not just getting it back — is what turns the kitchen line from survival into offense.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000043"), Title = "Return and Advance", Category = "Returns", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Partner serves; you return deep and immediately advance to the kitchen line, split-stepping as the third shot is struck. Play out the point from there. 15 reps per side. The return itself matters less than what follows it — this drill welds the deep return and the approach into one motion, the pattern you'll use on every single return for the rest of your pickleball life.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000044"), Title = "Defensive Lob Basics", Category = "Lobs", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Partner drives balls at you from the kitchen line while you defend from mid-court. Instead of blocking, throw up a high defensive lob deep enough to push them off the line, then use the time to recover position. 3 sets of 10. A good defensive lob isn't a winner — it's a rescue that turns a losing position back into a neutral one.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000045"), Title = "Mid-Court Reset Feeds", Category = "Resets", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "You stand in the transition zone; partner at the kitchen line hits medium-pace balls at your feet and body. Absorb each one with soft hands and float it into the kitchen, advancing a half-step whenever a reset lands well. 3 sets of 12. Getting stuck in mid-court is where beginners bleed points — the reset is how you buy your way forward.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000046"), Title = "High Ball Put-Away Volleys", Category = "Attacking", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Partner feeds floaters that arrive above net height at the kitchen line; you punch each one down into the open court or at the feeder's feet (with warning!). 3 sets of 10 per side. Recognizing an attackable ball — and actually attacking it instead of dinking it back — is the decision this drill trains. Anything below net height gets dinked; anything above gets hit.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000047"), Title = "Shuffle and Dink Along the Line", Category = "Movement", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 10,
            Description = "Partner drill. Dink cross-court while both players side-shuffle one position along the kitchen line after every two dinks — middle, wide, and back — keeping the rally alive while moving. 5-minute sets. Dinking from a stable base is easy; dinking while repositioning is the game. Feet first, paddle second.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000048"), Title = "Skinny Singles Rally Game", Category = "General", TargetDUPRLevel = 3.0m, EstimatedDurationMinutes = 20,
            Description = "Half-court singles game to 7: serve, return, and play out points using only one half of the court (both players on the same diagonal or same side). Every skill appears — serve, return, third shot, dinks, volleys — but with half the ground to cover, so rallies last long enough to actually practice them. Switch halves each game.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/how-to-play/basics/" },

        // 3.5 — Intermediate
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000005"), Title = "Third Shot Drop from Baseline", Category = "Drops", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "From the baseline, hit a third shot drop into the non-volley zone. Partner catches or lets it bounce. Focus on a low, soft arc that lands in the kitchen. Complete 3 sets of 10 reps each side.",
            SourceUrl = "https://pickleballkitchen.com/third-shot-drop/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000006"), Title = "Transition Zone Drop and Advance", Category = "Drops", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 15,
            Description = "Start at mid-court (transition zone). Hit a drop shot into the kitchen then advance to the kitchen line. Partner resets the ball from the kitchen. Repeat, practicing the split-step timing as you advance.",
            SourceUrl = "https://pickleballkitchen.com/transition-zone/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000007"), Title = "Dink Patterns: Straight and Cross", Category = "Dinking", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Partner drill: alternate between straight-ahead dinks and cross-court dinks in a structured pattern (2 straight, 2 cross). Helps develop shot placement awareness. Run for 5-minute sets.",
            SourceUrl = "https://pickleballkitchen.com/dinking-drills/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000008"), Title = "Backhand Reset Under Pressure", Category = "Resets", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Partner speeds up balls at your backhand from the kitchen. Your job is to absorb the pace and drop the ball softly into the kitchen — a reset. Focus on giving with the paddle on contact. 3 sets of 15.",
            SourceUrl = "https://3rdshotdrop.com/backhand-reset/" },

        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000049"), Title = "Aggressive Dink Targeting", Category = "Dinking", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Partner drill at the kitchen line. Instead of neutral dinks, aim every dink at a purpose: the backhand hip, the feet, or short-angle off the sideline. Partner does the same. Rally cooperatively but with intent — if a dink sits up, catch it and note who forced the error. 5-minute sets. This converts dinking from rally-survival into pressure-building.",
            SourceUrl = "https://pickleballkitchen.com/dinking-drills/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000050"), Title = "Drop vs Drive Decision Drill", Category = "Drops", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 15,
            Description = "Partner returns your feed with varying depth. Short mid-court returns you DRIVE at their body; deep returns you DROP into the kitchen. Call your choice out loud before contact. 3 sets of 15. The third shot isn't automatically a drop — it's a decision, and reading return depth is what this drill trains.",
            SourceUrl = "https://pickleballkitchen.com/third-shot-drop/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000051"), Title = "Spin Serve Development", Category = "Serving", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Practice adding topspin to your serve: brush low-to-high through contact, aiming deep to the backhand corner. 10 topspin serves per box, then 10 flat power serves for contrast, tracking depth and makes. A serve that kicks and stays deep sets up weak returns — the raw material for third shot drops that don't have to be perfect.",
            SourceUrl = "https://pickleballkitchen.com/dinking-drills/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000052"), Title = "Slice Return and Rush", Category = "Returns", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Partner serves; you hit a low, skidding slice return deep to the backhand side and follow it in to the kitchen line. The slice's slower flight buys you time to arrive set. Play out the point against the third shot. 15 reps per side, tracking how often you're established at the line before the third shot is struck.",
            SourceUrl = "https://pickleballkitchen.com/transition-zone/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000053"), Title = "Offensive Lob off the Dink", Category = "Lobs", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Dink rally at the kitchen line. Every 4–6 dinks, disguise an offensive lob: same low posture and backswing as a dink, then lift over your partner's backhand shoulder to land in the back quarter. Partner tracks and runs it down; play out the point. 3 sets of 10 lob attempts. The disguise matters more than the height — a telegraphed lob is an overhead waiting to happen.",
            SourceUrl = "https://pickleballkitchen.com/dinking-drills/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000054"), Title = "Transition Zone Reset Ladder", Category = "Resets", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 15,
            Description = "Partner attacks from the kitchen line while you reset from three stations: just behind the kitchen, mid transition zone, and near the baseline. Earn 3 successful resets (soft, unattackable, landing in the kitchen) at a station to advance one step forward; an attackable reset sends you back a station. Climb the ladder twice. Deeper court position means bigger swing discipline.",
            SourceUrl = "https://3rdshotdrop.com/backhand-reset/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000055"), Title = "Speed-Up Selection Drill", Category = "Attacking", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 15,
            Description = "Dink rally where you may only speed up a ball that arrives above net height — attack anything lower and you lose the point instantly. Partner counters or resets and play continues. Play games to 11. Most 3.5 players lose points by attacking unattackable balls; this drill makes shot selection the scoreboard.",
            SourceUrl = "https://pickleballmax.com/speed-up-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000056"), Title = "Drop and Advance Footwork Patterns", Category = "Movement", TargetDUPRLevel = 3.5m, EstimatedDurationMinutes = 10,
            Description = "Hit a third shot drop from the baseline, then advance behind it: two or three quick steps, split-step as your partner strikes their reply, continue in if it's a dink, hold and reset if it's an attack. Partner varies the response. 3 sets of 10 advances. Watching your drop instead of moving behind it is the classic 3.5 stall — this drill trains feet that trust the shot.",
            SourceUrl = "https://pickleballkitchen.com/transition-zone/" },

        // 4.0 — Advanced
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000009"), Title = "Speed-Up Attack and Counter", Category = "Attacking", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "Player A speeds up a ball at Player B's body. Player B counters back at Player A's feet. Rally continues until someone misses or resets. Develops quick reflexes and body-ball recognition. 5-minute continuous play.",
            SourceUrl = "https://pickleballmax.com/speed-up-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000010"), Title = "Erne Setup and Execution", Category = "Volleys", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Practice the Erne: dink cross-court to pull opponent wide, then jump around the post or step through the kitchen corner to volley from outside the NVZ. Shadow practice 10 times then live reps with a feeding partner.",
            SourceUrl = "https://pickleballmax.com/erne-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000011"), Title = "Advanced Third Shot Drop Sequences", Category = "Drops", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Baseline player hits third shot drops until one lands in the kitchen and is unattackable, then advances. Kitchen player applies pressure — speeds up anything above the net. Measures quality of drop under pressure. Competitive scoring.",
            SourceUrl = "https://pickleballkitchen.com/advanced-third-shot/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000012"), Title = "Competitive Dinking with Speed-Up Option", Category = "Dinking", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Cross-court dinking rally where either player can speed up at any time. The other player must counter or reset. Play to 11 points. Builds patience and the ability to recognize and create opportunities.",
            SourceUrl = "https://3rdshotdrop.com/competitive-dinking/" },

        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000057"), Title = "Fifth Shot Drop Consistency", Category = "Drops", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Serve-team pattern: drive the third shot at the kitchen player, who blocks it back to mid-court; you follow in and hit a fifth shot drop from the transition zone, then finish the advance. Play out the point. 3 sets of 10 sequences. The drive-then-drop (shake and bake without the poach) only works if the fifth shot lands soft — this drill isolates exactly that ball.",
            SourceUrl = "https://pickleballkitchen.com/advanced-third-shot/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000058"), Title = "Punch Volley Target Battle", Category = "Volleys", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "Both players at the kitchen line with cone targets placed at each other's feet and open hips. Exchange firm punch volleys aiming for targets — a cone hit or a forced pop-up scores a point. First to 11. Directed volleys at the feet and hips win firefights before they start; this drill keeps score on precision, not pace.",
            SourceUrl = "https://pickleballmax.com/speed-up-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000059"), Title = "Pressure Serve Percentages", Category = "Serving", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "Competitive serving under consequence: 20 serves at full match pace to called targets (wide, body, T), each must land in the back third. Score plus-one for a called-target make, minus-two for any fault. Finish positive or repeat the set. At 4.0 the serve is a weapon with a cost — this drill prices in the double-fault risk that scoreboard pressure creates.",
            SourceUrl = "https://pickleballmax.com/speed-up-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000060"), Title = "Deep Slice Return Under Pressure", Category = "Returns", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "Partner serves at full power, mixing placement and spin. You slice every return low and deep to a called corner and get to the kitchen line before the third shot. Track a make percentage over 20 returns; anything landing mid-court counts as a miss even if it's in. Against big servers, the return that skids low and deep is what keeps the serving team off the drive.",
            SourceUrl = "https://3rdshotdrop.com/competitive-dinking/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000061"), Title = "Lob and Overhead Battle", Category = "Lobs", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Point-play drill: one player throws up offensive lobs from the kitchen line, the other tracks back and answers with an overhead or a controlled reset lob; play out every point. Rotate roles every 5 points, games to 11. Trains both halves of the lob exchange — the disguise and placement going up, and the footwork (drop step, crossover, never backpedal) coming down.",
            SourceUrl = "https://pickleballmax.com/erne-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000062"), Title = "Firefight Reset Escape", Category = "Resets", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "Start a kitchen-line firefight at full speed. Your job is the opposite of winning it: at the first viable ball, kill the pace with a dead-hands reset that drops into the kitchen and forces the rally back to dinks. Score a point for each successful de-escalation, lose one for feeding an attackable ball. Games to 7. Elite hands aren't just fast — they know how to turn the temperature down.",
            SourceUrl = "https://3rdshotdrop.com/backhand-reset/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000063"), Title = "Two-Ball Speed-Up Combinations", Category = "Attacking", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 15,
            Description = "Work speed-ups as two-shot patterns, not single shots: attack the first ball to a chosen target (backhand shoulder, hip, feet), anticipate the counter, and finish the second ball to the open court. Partner counters at full effort; play out every exchange. 3 sets of 10 initiations per player. At 4.0 the first speed-up rarely wins — plan the combination, not the shot.",
            SourceUrl = "https://pickleballmax.com/speed-up-drill/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000064"), Title = "Transition Zone Defense Footwork", Category = "Movement", TargetDUPRLevel = 4.0m, EstimatedDurationMinutes = 10,
            Description = "You advance from the baseline while your partner at the kitchen line drives balls at you without pause. Split-step at each strike, absorb what comes at you, advance only behind a ball you've made unattackable, hold or retreat a half-step otherwise. 3 sets of 10 approaches, scoring how often you reach the line without popping one up. Forward progress is earned per shot, not assumed.",
            SourceUrl = "https://pickleballkitchen.com/transition-zone/" },

        // 5.0 — Professional
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000013"), Title = "ATP and Roll Volley Combination", Category = "Attacking", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Advanced tournament drill: partner feeds wide balls to practice the Around-The-Post (ATP) shot followed immediately by a roll volley to the open court. Execute 20 reps each side with correct footwork and follow-through.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000014"), Title = "Full-Court Scenario Game Simulation", Category = "General", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 20,
            Description = "Professional-level competitive rally simulation: points start with a serve and play out at full pace. Emphasis on pattern play — third shot, advance, reset if needed, find and attack the first pop-up. Analyze patterns after each point. Best of 21.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000015"), Title = "High-Level Firefight Training", Category = "Volleys", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 10,
            Description = "Both players at kitchen line engaging in rapid-fire speed-up exchanges. No resets allowed — must counter or win the point. Trains competitive fast-hands reflexes at professional pace. 10-point games with full tracking.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000016"), Title = "Serve plus Tournament Pattern Play", Category = "Serving", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 20,
            Description = "Professional serve targeting: practice power serves to T, body, and wide positions, each followed by a planned third shot pattern (drop vs. drive decision based on return depth). Full match-simulation pressure with scoring.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000065"), Title = "Pressure Dinking with Zone Penalties", Category = "Dinking", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Tournament-pace dink game to 11 with called target zones: each dink must land in the currently called zone (backhand-side kitchen, sideline third, at the feet). Hitting the wrong zone or sitting one up loses the point outright; either player may speed up a legitimately attackable ball at any time. Precision under a live attack threat — dinking the way it exists at 5.0.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000066"), Title = "Third and Fifth Shot Precision Circuit", Category = "Drops", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 20,
            Description = "Timed circuit: 10 third shot drops from the baseline into a paddle-width target strip in the kitchen, 10 fifth shot drops from the transition zone under live kitchen-line pressure, 10 drops off the run from the sideline. Restart any set where fewer than 7 land unattackable. Full circuit twice. Tournament drops aren't hit from a stance — they're hit from wherever the last shot left you.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000067"), Title = "Return Depth Pinning Game", Category = "Returns", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Live points where every return must land in the back three feet of the court — a shorter return means the point restarts and the returner loses a point. Server plays full-speed drives or drops off anything short. Games to 11. At tournament level a mid-court return is a lost rally; this game makes the returner feel that price on every single ball.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000068"), Title = "Tournament Lob and Cover Rotation", Category = "Lobs", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Doubles pattern drill: the offensive lob goes up over one kitchen-line player's shoulder, their partner tracks it down while the lobbed player switches sides, and the point plays out against a full-speed attack on the recovery ball. Rotate all four positions. 20 total sequences. Trains disguised lobs, partner communication ('switch!'), and the overhead-versus-reset decision at match pace.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000069"), Title = "Full-Speed Reset Gauntlet", Category = "Resets", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "You defend from mid-court while two attackers (or one, rapid-feeding) hit maximum-pace put-aways at your body and feet. Survive by resetting into the kitchen; three consecutive unattackable resets earns your way to the kitchen line and the point restarts. Score gauntlet completions in 15 minutes. Defense at 5.0 means neutralizing balls most players wouldn't touch.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000070"), Title = "Firefight Finish Patterns", Category = "Attacking", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Scripted attack sequences at full speed: initiate with a speed-up to the backhand shoulder, counter the counter to the hip, finish to the open court — then run the mirror pattern. Partner defends live; any pattern ball that misses its target restarts the rep. 10 clean sequences per pattern, per player. Pros don't win firefights with reflexes alone — they win with pre-decided sequences.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000071"), Title = "Court Coverage Scramble Simulation", Category = "Movement", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 15,
            Description = "Partner (or coach) feeds a brutal sequence with no rhythm: deep drive, short drop, wide angle, lob, body speed-up. You play every ball with full recovery footwork between shots — split-step, push-off, recover to the tactically correct position, not just center. 3 sets of 2 minutes at match intensity. Tournament movement is defined by the worst ball you can still cover.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
        new Drill { Id = Guid.Parse("a1000000-0000-0000-0000-000000000072"), Title = "Constraint Match Play", Category = "General", TargetDUPRLevel = 5.0m, EstimatedDurationMinutes = 20,
            Description = "Full match-pace games to 11 with a rotating constraint each game: every third shot must be a drop; no drives allowed; all speed-ups must target the backhand; one player must take every ball possible out of the air. Constraints force pattern depth you'd never choose voluntarily — the point is discovering which tools hold up when your favorite one is confiscated.",
            SourceUrl = "https://usapickleball.org/what-is-pickleball/official-rules/" },
    };
}
